int bitParity(int);
int test_bitParity(int);
int rotateRight(int, int);
int test_rotateRight(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int fitsShort(int);
int test_fitsShort(int);
int isGreater(int, int);
int test_isGreater(int, int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int isTmax(int);
int test_isTmax(int);
